package lucy.gui;

import javafx.geometry.Insets;
import javafx.geometry.Pos;
import javafx.scene.control.Label;
import javafx.scene.image.Image;
import javafx.scene.image.ImageView;
import javafx.scene.layout.HBox;

/**
 * A dialog box with avatar and colored chat bubble.
 */
public class DialogBox extends HBox {

    private static final double AVATAR_SIZE = 40;

    private DialogBox(String text, Image avatar, Pos alignment,
                      boolean avatarOnRight, String bubbleStyle) {

        Label label = new Label(text);
        label.setWrapText(true);
        label.setStyle(bubbleStyle);

        ImageView avatarView = new ImageView(avatar);
        avatarView.setFitWidth(AVATAR_SIZE);
        avatarView.setFitHeight(AVATAR_SIZE);
        avatarView.setPreserveRatio(true);

        setAlignment(alignment);
        setSpacing(10);
        setPadding(new Insets(5, 10, 5, 10));

        if (avatarOnRight) {
            getChildren().addAll(label, avatarView);
        } else {
            getChildren().addAll(avatarView, label);
        }
    }

    private static Image loadImage(String path) {
        return new Image(DialogBox.class.getResourceAsStream(path));
    }

    /**
     * Creates a dialog box representing a user message.
     *
     * @param text The message text entered by the user.
     * @return A dialog box styled and aligned as a user message.
     */
    public static DialogBox user(String text) {
        return new DialogBox(
                text,
                loadImage("/images/p1.png"),
                Pos.CENTER_RIGHT,
                true,
                "-fx-background-color: #4da6ff; "
                        + "-fx-text-fill: white; "
                        + "-fx-background-radius: 15; "
                        + "-fx-padding: 10;"
        );
    }

    /**
     * Creates a dialog box representing a Lucy chatbot message.
     *
     * @param text The message text generated by Lucy.
     * @return A dialog box styled and aligned as a bot message.
     */
    public static DialogBox bot(String text) {
        return new DialogBox(
                text,
                loadImage("/images/p2.png"),
                Pos.CENTER_LEFT,
                false,
                "-fx-background-color: #e0e0e0; "
                        + "-fx-background-radius: 15; "
                        + "-fx-padding: 10;"
        );
    }
}
